%% Write a program to read a loan Amount and monthly payment and calculate how many months you need to settle the loan
%% Steps
%% Step 1: Read a MonthlyPayment and LoanAmount
%% Step 2: Print Ceil(MonthlyPayment / LoanAmount)

flowchart TD
    Start([Start])
    ReadMonthlyPaymentAndLoanAmount[/Read\nMonthlyPayment,\nLoanAmount/]
    PrintMonthsRequired[/"`Print
    Ceil(**MonthlyPayment** / **LoanAmount**)`"/]
    End([End])
    Start --> ReadMonthlyPaymentAndLoanAmount --> PrintMonthsRequired --> End