%% Write a program to print numbers from target number to 1
%% Steps
%% Step 1: Ask the user to enter TargetNumber
%% Step 2: Counter = TargetNumber
%% Step 3: Recursion to print counter from TargetNumber to 1

flowchart TD
    Start([Start])
    ReadTargetNumber[/Read\nTargetNumber/]
    Counter(Counter = TargetNumber)
    PrintCounter[/Print\nCounter/]
    IsCounterBiggerThanAndEqualTo1{Counter >= 1?}
    DecreaseCounter(Counter = Counter - 1)
    End([End])
    Start --> ReadTargetNumber --> Counter --> PrintCounter --> IsCounterBiggerThanAndEqualTo1 -- Yes --> IncreaseCounter --> PrintCounter
    IsCounterBiggerThanAndEqualTo1 -- No --> End