%% Write a program to read a loan Amount and ask you how many months you need to settle the loan, Then calculate the monthly installment amount
%% Steps
%% Step 1: Read a LoanAmount, Months
%% Step 2: Print LoanAmount / Months

flowchart TD
    Start([Start])
    ReadLoanAmountAndMonths[/Read\nLoanAmount,\nMonths/]
    PrintMonthlyPayment[/"`Print
    **LoanAmount** / **Months**`"/]
    End([End])
    Start --> ReadLoanAmountAndMonths --> PrintMonthlyPayment --> End