%% Write a program to calculate circle area then print it on the screen
%% Steps
%% Step 1: Ask the user to enter Radius
%% Step 2: PI = 3.14
%% Step 3: Area = PI * R * R
%% Step 4: Print Area

flowchart TD
    Start([Start])
    ReadRadius[/Read\nRadius/]
    PI(PI = 3.14)
    Area("`Area = PI * **Radius** * **Radius**`")
    PrintArea[/Print\nArea/]
    End([End])
    Start --> ReadRadius --> PI --> Area --> PrintArea --> End