%% Write a program to print your name on screen
%% Steps
%% Step 1: Print "Mohamed"

flowchart TD
    Start([Start])
    printMohamed[/Print\nMohamed/]
    End([End])
    Start --> printMohamed --> End