%% Write a program to ask the user to enter a number, Then print "Odd" if its odd, Or "Even" if its even
%% Steps
%% Step 1: Ask the user to enter a number
%% Step 2: Check if (Number mod 2 = 0?) then its even otherwise its odd
%% Step 3: Print "Odd" or "Even" accordingly

flowchart TD
    Start([Start])
    ReadNumber[/Read\nNumber/]
    isEven{Number mod 2 = 0?}
    PrintEven[/Print\nEven/]
    PrintOdd[/Print\nOdd/]
    End([End])
    Start --> ReadNumber --> isEven -- Yes --> PrintEven --> End
    isEven -- No --> PrintOdd --> End