%% Write a program to calculate rectangle area and print it on the screen
%% Steps
%% Step 1: Ask the user to enter (Length, Width)
%% Step 2: Area = Length * Width
%% Step 3: Print Area

flowchart TD
    Start([Start])
    ReadTwoNumbers[/Read\nLength,\nWidth/]
    Area(Area = Length * Width)
    PrintArea[/Print\nArea/]
    End([End])
    Start --> ReadTwoNumbers --> Area --> PrintArea --> End