%% Write a program to ask the user to enter
%% • Number
%% • Exponent
%% Then print the Number^Exponent
%% Steps
%% Step 1: Ask the user to enter Number
%% Step 2: If Number = 0 then Print 0
%% Step 3: If Exponent = 1 then Print Number
%% Step 4: Counter = 2
%% Step 5: Power = Number * Number
%% Step 6: Recursion (Power = Power * Number) if Counter less than and equal Exponent, from 2 to Exponent
%% Step 7: Print Power

flowchart TD
    Start([Start])
    ReadNumberAndExponent[/Read\nNumber,\nExponent/]
    IsNumberEqualTo0{Number = 0?}
    Print0[/Print\n0/]
    IsExponentEqualTo1{Exponent = 1?}
    PrintNumber[/Print\nNumber/]
    Counter[/Counter = 3/]
    Power[/Power = Number * Number/]
    IsCounterLessThanAndEqualExponent{Counter <= Exponent}
    IncreasePower[/Power = Power * Number/]
    IncreaseCounter[/Counter = Counter + 1/]
    PrintPower[/Print\nPower/]
    End([End])
    Start --> ReadNumberAndExponent --> IsNumberEqualTo0 -- Yes --> Print0 --> End
    IsNumberEqualTo0 -- No --> IsExponentEqualTo1 -- Yes --> PrintNumber --> End
    IsExponentEqualTo1 -- No --> Counter --> Power --> IsCounterLessThanAndEqualExponent -- Yes --> IncreasePower --> IncreaseCounter --> IsCounterLessThanAndEqualExponent
    IsCounterLessThanAndEqualExponent -- No --> PrintPower --> End