%% Write a program to calculate circle area Inscribed in an Isosceles, Then print it on screen
%% Steps
%% Step 1: Ask the user to enter (EqualSidesLength, Base)
%% Step 2: PI = 3.14
%% Step 3: Area = PI * Base * Base / 4 * ((2 * EqualSidesLength - Base) / (2 * EqualSidesLength + Base))
%% Step 4: Print Area

flowchart TD
    Start([Start])
    ReadEqualSidesAndBase[/Read\nEqualSidesLength,\nBase/]
    PI(PI = 3.14)
    Area("`Area = **PI** * **Base** * **Base** / 4 * ((2 * **EqualSidesLength** - **Base**) / (2 * **EqualSidesLength** + **Base**))`")
    PrintArea[/Print\nArea/]
    End([End])
    Start --> ReadEqualSidesAndBase --> PI --> Area --> PrintArea --> End